Begin of work on modularization.

diff --git a/pacmoon b/pacmoon
--- a/pacmoon
+++ b/pacmoon
@@ -59,8 +59,20 @@ is_installed() {
 	grep -q "^$1$" /var/lib/pkg/db
 }
 
+is_installed_as_dep() {
+	false
+}
+
 get_architecture() {
 	crux | cut -d " " -f 2
+}
+
+builder() {
+	as_root pkg++ $mkpkg_args
+}
+
+packages_installer() {
+	pkg++ -i -u
 }
 
 #/FIXME
@@ -158,8 +170,7 @@ typeset -a abs_failed
 typeset -a abs_badv
 
 is_dep() {
-	# FIXME: pacman -Qe tells if the package was installed on the user’s request or as a dependency
-	[[ $+requested_pkgs[$1] -eq 0 ]] && ! pacman &>/dev/null -Qe $1
+	[[ $+requested_pkgs[$1] -eq 0 ]] && ! is_installed_as_dep $1
 }
 
 is_rebuild() {
@@ -173,33 +184,23 @@ build_pkg() {
 		die "could not cd to $pmoonHome/tmp/$name"
 	rm -rf src
 
-	typeset -a mkpkg_args
-	mkpkg_args=(-f)
-	if [[ $+split_pkgs[$name] -eq 1 ]] ; then
-		# fullname only set for split packages
-		mkpkg_args=($mkpkg_args --pkg "$split_pkgs[$name]")
-	fi
-
 	if is_dep $pkg ; then
 		local as_dep
 	fi
 
-	log_info "build ${as_dep+dependency }package $name ($mkpkg_args)"
+	log_info "build ${as_dep+dependency }package $name"
 
 	rm -f *.pkg.tar.*
 	if [[ $+quiet -eq 1 ]] ; then
-		as_root pkg++ &>/dev/null $mkpkg_args
+		as_root builder &>/dev/null
 	else
-		as_root pkg++ $mkpkg_args
+		as_root builder
 	fi
 
 	[[ $? -eq 0 ]] || die "could not build $name"
 
-	# TODO: test split packages one by one
-	#as_root pacman --noconfirm -U ${as_dep+--asdeps} *.pkg.tar.* || \
-	#	die "could not install package"
-	# FIXME: This sucks.
-	as_root pkg++ -i -u
+	as_root packages_installer || \
+		die "could not install package"
 
 	# record the date the package was dep_status
 	get_installation_date $name > "$pmoonHome/pkg/$name"
@@ -248,7 +249,6 @@ resolve_name() {
 		echo "$pkgData"
 	fi
 }
-
 
 collect_pkg_data() {
 	local name=$1
@@ -353,7 +353,7 @@ as_root() {
 processing_pkg() {
 	if [[ $+dep_status[$1] -eq 1 ]] ; then
 		if [[ $dep_status[$1] -eq 2 ]] ; then
-			pacman &>/dev/null -Q $1 || cyclic_deps+=$1
+			is_installed $1 || cyclic_deps+=$1
 			dep_status[$1]=1
 		fi
 		return 1
@@ -423,12 +423,12 @@ build_pkgs() {
 	fi
 
 	for pkg in $cyclic_deps ; do
-		as_root pacman --asdeps --needed --noconfirm -S $pkg || die \
+		as_root dependencies_installer $pkg || die \
 			"could not get binary package for recursive dependency $pkg"
 	done
 
 	for pkg in ${(k)makedep_pkgs} ; do
-		as_root pacman --asdeps --needed --noconfirm -S $pkg
+		as_root dependencies_installer $pkg
 	done
 
 	for pkg ver in "${(@)install_pkgs}" ; do
